export const GET_PRODUCT_REQUVEST = " GET_PRODUCT_REQUVEST"
export const GET_PRODUCT_SUCCESS = " GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_ERROR = " GET_PRODUCT_ERROR"

export const ADD_PRODUCT_REQUVEST = " ADD_PRODUCT_REQUVEST"
export const ADD_PRODUCT_SUCCESS = " ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_ERROR = " ADD_PRODUCT_ERROR"

export const DELETE_PRODUCT_REQUVEST = " DELETE_PRODUCT_REQUVEST"
export const DELETE_PRODUCT_SUCCESS = " DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_ERROR = " DELETE_PRODUCT_ERROR"

export const UPDATE_PRODUCT_REQUVEST = " UPDATE_PRODUCT_REQUVEST"
export const UPDATE_PRODUCT_SUCCESS = " UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_ERROR = " UPDATE_PRODUCT_ERROR"


export const GET_SINGLE_PRODUCT = " GET_SINGLE_PRODUCT"
// export const GET_PRODUCT_SUCCESS = " GET_PRODUCT_SUCCESS"
// export const GET_PRODUCT_ERROR = " GET_PRODUCT_ERROR"
